accounting/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
import accounting.views
urlpatterns = patterns('',
    url(r'^addpultdata/$', accounting.views.UploadControlData.
    as_view(), {}, 'upload-new-pultdata'),
    url(r'^addbilldata/$', accounting.views.UploadBillData.as_view(
    ), {}, 'upload-new-billdata'),
    url(r'^addincomedata/$', accounting.views.UploadIncomeData.
    as_view(), {}, 'upload-new-incomedata'),
    url(r'^addoutcomedata/$', accounting.views.UploadOutcomeData.
    as_view(), {}, 'upload-new-outcomedata'),
    url(r'^cards_list/page(?P<page>\d+)/(?P<month>\d+)/(?P<year>\d+)/',
        accounting.views.CardsView.as_view(), {}, 'cards-list'),
    url(r'^export/(?P<month>\d+)/(?P<year>\d+)/', accounting.views.
    ExportXLS.as_view(), {}, 'export'),
    url(r'^setfilter/(?P<filter_type>\w+)/(?P<filter_parameter>[^/]+)/$',
        accounting.views.EnableFilterView.as_view(), {}, 'set-filter'),
    url(r'^cards_list-income/', RedirectView.as_view(
        url='/admin/accounting/incomeobject'), {}, 'cards-list-income'),
    url(r'^cards_list-outcome/', RedirectView.as_view(
        url='/admin/accounting/outcomeobject'), {}, 'cards-list-outcome'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', login_required(TemplateView.as_view(template_name='base.html'))),
    url(r'^accounts/login/$','django.contrib.auth.views.login',{'template_name': 'login.html'},name='login'),
    url(r'^accounts/logout/','django.contrib.auth.views.logout',{'next_page': '/',},name='logout'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/', include('accounting.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        'show_indexes': True}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
)
urlpatterns += patterns('django.contrib.staticfiles.views',url(r'^static/(?P<path>.*)$', 'serve'),)

urlpatterns+=staticfiles_urlpatterns()

accounting/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver
from datetime import datetime


class Branch(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'Название филиала', primary_key=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Филиал'
        verbose_name_plural = u'Филиалы'


class Card(models.Model):
    number = models.CharField(max_length=12, verbose_name=u'Номер карты', primary_key=True)
    state = models.CharField(max_length=1, choices=(
            ('R', 'Резерв'),
            ('W', 'Работает'),
            ('F', 'Свободна'),
        ), verbose_name=u'Состояние карты'
    )
    new_state = models.CharField(max_length=1, choices=(
            ('R', 'Резерв'),
            ('W', 'Работает'),
            ('F', 'Свободна'),
        ), verbose_name=u'Новое состояние карты'
    )
    branch = models.ForeignKey(Branch, verbose_name=u'Филиал', blank=True, null=True)
    P_accepted = models.BooleanField(default=False, verbose_name=u'Новое состояние подтверджено пультом')
    OD_accepted = models.BooleanField(default=False, verbose_name=u'Новое состояние подтверджено отделом договоров')
    B_accepted = models.BooleanField(default=False, verbose_name=u'Новое состояние подтверджено бухгалтерией')

    def get_bill_by_month(self, month, year):
        return [x.cost for x in self.bills_set.filter(Q(date__month=month) & Q(date__year=year))]

    def __unicode__(self):
        return self.number

    def get_absolute_url(self):
        return "/admin/accounting/card/{0}/".format(self.number)

    class Meta:
        verbose_name = u'Карта'
        verbose_name_plural = u'Карты'


class Hub(models.Model):
    number = models.CharField(max_length=50, verbose_name=u'Номер концентратора', primary_key=True)

    def __unicode__(self):
        return self.number

    class Meta:
        verbose_name = u'Концентратор'
        verbose_name_plural = u'Концентраторы'


class Contract(models.Model):
    number = models.CharField(max_length=12, verbose_name=u'Номер договора', primary_key=True)
    date = models.DateField(verbose_name=u'Дата заключения')
    contracted = models.CharField(max_length=120, verbose_name=u'С кем заключен')
    hub = models.ForeignKey(Hub, verbose_name=u'Концентратор')

    def __unicode__(self):
        return self.number

    class Meta:
        verbose_name = u'Договор'
        verbose_name_plural = u'Договора'


class Object(models.Model):
    hub = models.ForeignKey(Hub, verbose_name=u'Концентратор', blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name=u'Название обьекта')
    cards = models.ManyToManyField(Card, verbose_name=u'Карта', blank=True, null=True)
    branch = models.ForeignKey(Branch, verbose_name=u'Филиал', blank=True, null=True)
    address = models.CharField(max_length=120, verbose_name=u'Адрес обьекта')
    contract = models.ForeignKey(Contract, verbose_name=u'Договор', blank=True, null=True)
    not_alive = models.BooleanField(default=False, verbose_name=u"Обьект удален")
    delete_date = models.DateField(blank=True, null=True, default=None, verbose_name=u"Дата удаления")

    def __unicode__(self):
        return u"{0} , {1}".format(self.name, self.address)

    class Meta:
        ordering=['-delete_date']
        verbose_name = u'Обьект'
        verbose_name_plural = u'Обьекты'


class Bills(models.Model):
    card = models.ForeignKey(Card, verbose_name=u'Карта')
    date = models.DateField(verbose_name=u'Дата счета')
    cost = models.FloatField(verbose_name=u'Сумма счета')
    ordering = ('card',)

    def __unicode__(self):
        return u"{0} : {1}".format(self.card, self.date)

    class Meta:
        verbose_name = u'Счет'
        verbose_name_plural = u'Счета'


class IncomeObject(models.Model):
    object = models.ForeignKey(Object)

    class Meta:
        verbose_name = u'Взятый'
        verbose_name_plural = u'Взятые'


class OutcomeObject(models.Model):
    object = models.ForeignKey(Object)

    class Meta:
        verbose_name = u'Ушедший'
        verbose_name_plural = u'Ушедшие'


@receiver(pre_save, sender=Card)
def inspect_status_card(instance, **kwargs):
    if isinstance(instance, Card):
        try:
            old_instance = Card.objects.get(pk=instance.pk)
            if instance.state != instance.new_state and instance.new_state != old_instance.new_state:
                instance.B_accepted = False
                instance.OD_accepted = False
                instance.P_accepted = False

            elif instance.state != instance.new_state and reduce(lambda x, q: x and q, [instance.B_accepted, instance.OD_accepted, instance.P_accepted]):
                instance.state = instance.new_state
        except:
            pass

accounting/forms.py
__author__ = 'lex'
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(required=True)

accounting/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView
from django.views.generic import ListView, View
from accounting.forms import UploadFileForm
from accounting.models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import simplejson
from django.db.transaction import commit_on_success
from django.conf import settings
from django.core.urlresolvers import reverse
from os import path
import xlwt


def response_mimetype(request):
    if "application/json" in request.META['HTTP_ACCEPT']:
        return "application/json"
    else:
        return "text/plain"


class JSONResponse(HttpResponse):
    """JSON response class."""
    def __init__(self, obj='', json_opts={}, mimetype="application/json", *args, **kwargs):
        content = simplejson.dumps(obj, **json_opts)
        super(JSONResponse, self).__init__(content, mimetype, *args, **kwargs)


class UploadControlData(FormView):
    form_class = UploadFileForm
    success_url = '/'
    template_name = 'uploadformpult.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return  super(UploadControlData, self).dispatch(request, *args, **kwargs)

    @commit_on_success
    def form_valid(self, form):
        in_file = self.request.FILES['file']
        filename = in_file.name
        parser = None
        if filename == u'Дунай.txt':
            from parsers import parser_Dunai
            parser = parser_Dunai.Parser()
        if filename == u'Грифон.txt':
            from parsers import parser_Grifon
            parser = parser_Grifon.Parser()
        if filename == u'ФЕНИКС.xls':
            from parsers import parser_fenix
            parser = parser_fenix.Parser()
        if filename == u'Феникс пожарка.xls':
            from parsers import parser_fenix_pojarka
            parser = parser_fenix_pojarka.Parser()
        if filename == u'Мост Чернигов.xls':
            from parsers import parser_most_chernigov
            parser = parser_most_chernigov.Parser()
        filepath = self.request.FILES['file'].temporary_file_path()
        data = parser(filepath)
        for item in data:
            hub = Hub.objects.get_or_create(pk=item[0])[0]
            hub.save()
            card, created = Card.objects.get_or_create(
                pk=item[3],
                defaults={
                    'state': 'W',
                    'new_state': 'W',
                    'P_accepted': True,
                    'OD_accepted': True,
                    'B_accepted': True,
                }
            )
            if not item[3]:continue
            card.save()
            _object, created = Object.objects.get_or_create(
                hub=hub,
                name = item[1],
                address = item[2],
            )
            _object.cards.add(card,)
            _object.save()
        data = [{u'name': filename, u'success': True}]
        response = JSONResponse(data, {}, response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class UploadBillData(FormView):
    form_class = UploadFileForm
    success_url = '/'
    template_name = 'uploadformbill.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return  super(UploadBillData, self).dispatch(request, *args, **kwargs)

    @commit_on_success
    def form_valid(self, form):
        in_file = self.request.FILES['file']
        filename = in_file.name
        parser = None
        if  'xls' in filename:
            from parsers import parser_kievstar
            parser = parser_kievstar.Parser()
        if 'htm' in filename:
            from parsers import HTML_parse
            parser = HTML_parse.Parser()
        filepath = self.request.FILES['file'].temporary_file_path()
        data = parser(filepath)
        for item in data:
            card, created = Card.objects.get_or_create(
                pk=item[0],
                defaults={
                    'state': 'W',
                    'new_state': 'W',
                    'P_accepted': True,
                    'OD_accepted': True,
                    'B_accepted': True,
                }
            )
            if created:
                card.save()
            _bills, created = Bills.objects.get_or_create(
                card=card,
                date=item[1],
                defaults={
                    'cost': item[2]
                }

            )
            _bills.save()
        data = [{u'name': filename, u'success': True}]
        response = JSONResponse(data, {}, response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class CardsView(ListView):
    model = Card
    template_name = 'cards.html'
    context_object_name = 'cards'
    paginate_by = 20
    allow_empty = True

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.year = kwargs['year']
        self.month = kwargs['month']
        if not request.META.get('HTTP_REFERER', False):
            request.session['filter'] = {}
            request.session['filter']['type'] = 'none'
        return  super(CardsView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if not self.request.session.get('filter', False) or self.request.session['filter']['type'] == 'none':
            #TODO:// Bad and slow query, replace this shet
            #queryset = Card.objects.extra(select={'cost': "select accounting_bills.cost from accounting_bills  where accounting_bills.date = '{0}-{1}-01' and accounting_bills.card_id in (select accounting_object_cards.card_id from accounting_object_cards where accounting_object_cards.object_id=accounting_card.number)".format(str(self.year), str(self.month))})
            #return  [x for x in queryset if x.cost]
            bills = Bills.objects.filter(
                Q(date__month=str(self.month)) &
                Q(date__year=str(self.year))
            )#.prefetch_related('card')
            return [x.card for x in bills]
        if self.request.session['filter']['type'] == 'order':
            if self.request.session['filter']['parameter'] == 'minmax':
                #TODO:// Bad and slow query, replace this shet
                #queryset = Card.objects.extra(
                #    select={'cost': "select accounting_bills.cost from accounting_bills  where accounting_bills.date = '{0}-{1}-01' and accounting_card.number = accounting_bills.card_id".format(str(self.year), str(self.month))}
                #).order_by('cost')
                #return  [x for x in queryset if x.cost]
                bills = Bills.objects.filter(
                    Q(date__month=str(self.month)) &
                    Q(date__year=str(self.year))
                ).order_by('cost')
                return  [x for x in bills if x.cost]
            else:
                #TODO:// Bad and slow query, replace this shet
                #queryset = Card.objects.extra(select={'cost': "select accounting_bills.cost from accounting_bills  where accounting_bills.date = '{0}-{1}-01' and accounting_card.number = accounting_bills.card_id".format(str(self.year), str(self.month))}).order_by('-cost')
                #return  [x for x in queryset if x.cost]
                bills = Bills.objects.filter(
                    Q(date__month=str(self.month)) &
                    Q(date__year=str(self.year))
                ).order_by('-cost')
                return  [x for x in bills if x.cost]
        if self.request.session['filter']['type'] == 'filial':
            branch = Branch.objects.filter(name__startswith=self.
                                                            request.session['filter']['parameter'])
            return ([x for x in branch[0].card_set.all()] if len(branch) else [])

        if self.request.session['filter']['type'] == 'limit':
            bills = Bills.objects.filter(
                Q(date__month=str(self.month)) &
                Q(date__year=str(self.year)) &
                Q(cost__gt=int(self.request.session['filter']['parameter']))
            ).prefetch_related('card')
            return [x.card for x in bills]

        if self.request.session['filter']['type'] == 'state':
            return  Card.objects.filter(Q(state__exact='F')|Q(state__exact='R'))

    def get_context_data(self, **kwargs):

        context = super(CardsView, self).get_context_data(**kwargs)
        context['years'] = [str(x) for x in range(2012, 2012 + 61)]
        context['year'] = str(self.year)
        try:
            if self.request.session['filter']['type'] == 'limit':
                context['limit'] = self.request.session[
                                   'filter']['parameter'] or '0'
            else:
                context['limit'] = settings.COST_LIMIT
        except:
            context['limit'] = settings.COST_LIMIT
        context['month'] = str(self.month)
        context['date'] = ';'.join([str(self.month), str(self.year)])
        context['filials'] = Branch.objects.all()
        context['overlimit'] = Bills.objects.filter(Q(date__month=str(self.month)) & Q(date__year=str(self.year)) & Q(cost__gt=settings.COST_LIMIT)).count()
        return context


class EnableFilterView(View):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.filter_type = kwargs['filter_type']
        self.filter_parameter = kwargs['filter_parameter']
        return  super(EnableFilterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        request.session['filter'] = {}
        request.session['filter']['type'] = self.filter_type
        request.session['filter']['parameter'] = self.filter_parameter
        year, month = '', ''

accounting/templates/cards.html
{% extends 'base.html' %}
{% load template_filters %}
{% block content %}

    <div class="container">
        <form class="well form-inline">
            <label class="control-label" for="select_month">Выберите месяц</label>
            <select id="select_month"  name="month">
                <option value="01"  {% ifequal '01' month %}selected="selected"{% endifequal %}>Январь</option>
                <option value="02"  {% ifequal '02' month %}selected="selected"{% endifequal %}>Февраль</option>
                <option value="03"  {% ifequal '03' month %}selected="selected"{% endifequal %}>Март</option>
                <option value="04"  {% ifequal '04' month %}selected="selected"{% endifequal %}>Апрель</option>
                <option value="05"  {% ifequal '05' month %}selected="selected"{% endifequal %}>Май</option>
                <option value="06"  {% ifequal '06' month %}selected="selected"{% endifequal %}>Июнь</option>
                <option value="07"  {% ifequal '07' month %}selected="selected"{% endifequal %}>Июль</option>
                <option value="08"  {% ifequal '08' month %}selected="selected"{% endifequal %}>Август</option>
                <option value="09"  {% ifequal '09' month %}selected="selected"{% endifequal %}>Сентябрь</option>
                <option value="10"  {% ifequal '10' month %}selected="selected"{% endifequal %}>Октябрь</option>
                <option value="11"  {% ifequal '11' month %}selected="selected"{% endifequal %}>Ноябрь</option>
                <option value="12"  {% ifequal '12' month %}selected="selected"{% endifequal %}>Декабрь</option>
            </select>
            <label class="control-label" for="select_year">Выберите год</label>
            <select id="select_year"  name="year">
                {% for y in years %}
                    <option value="{{ y }}" {% ifequal y year %}selected="selected"{% endifequal %}>{{ y }}</option>
                {% endfor %}
            </select>
        <a class="btn btn-primary" onclick="document.location = '../../'+$('#select_month')[0].options[$('#select_month')[0].selectedIndex].value+'/'+$('#select_year')[0].options[$('#select_year')[0].selectedIndex].value+'/ ';">Выбрать дату</a>
        </form>
        <section class="well">
            <div class="btn-group"  data-toggle="buttons-checkbox">
                <a class="btn {% ifequal filter.parameter 'none' %} active btn-success {% else %} btn-info {% endifequal %} "  href="{% url set-filter 'none','none' %}">Выбрать все </a>
                <a class="btn  {% ifequal filter.parameter 'minmax' %} active btn-success{% else %} btn-info {% endifequal %}"  href="{% url set-filter 'order','minmax' %}">Сортировать по расходам &darr;</a>
                <a class="btn {% ifequal filter.parameter 'maxmin' %} active btn-success{% else %} btn-info {% endifequal %}"  href="{% url set-filter 'order','maxmin' %}">Сортировать по расходам &uarr;</a>
                <a class="btn{% ifequal filter.parameter 'free' %} active btn-success{% else %} btn-info {% endifequal %}"  href="{% url set-filter 'state','free'%}">Свободные</a>
                {% if overlimit %}
                <a class="btn btn-info"  href="{% url set-filter 'limit',100 %}"><i class=" icon-warning-sign"></i>Лимит в 100 грн превышен у {{ overlimit }} карточек</a>
                {% endif %}
            </div>
        </section>

        <section class="well row" style="margin-left: 0px;">
            {% if filials|first %}
                <div class='span5'>
                    <div class="control-group form-horizontal">
                        <a id="fbyf"  class="btn {% ifequal filter.type 'filial' %} active btn-success{% else %} btn-info {% endifequal %}"  href="{% url set-filter 'filial',filials|first %}">Отобрать по филиалу</a>
                        <select id="filial"  name="filial" onchange="$('a#fbyf')[0].href = '{% url set-filter 'filial','forrep'%}'.replace('forrep',$('#filial')[0].options[$('#filial')[0].selectedIndex].value);">
                            {% for f in filials %}
                                <option value="{{ f.name }}">{{ f.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            {% endif %}
            <div class="span5">
                <div class="control-group form-horizontal">
                    <a id="limit"  class="btn {% ifequal filter.type 'limit' %} active btn-success{% else %} btn-danger  {% endifequal %}"  href="{% url set-filter 'limit',limit %}">Превышен лимит в</a>
                    <div class="input-append">
                        <input class="span2" id="appendedInput" size="16" type="text" value="{{ limit }}" oninput="$('#limit')[0].href = '{% url set-filter 'limit',0 %}'.replace('0',$(this).prop('value'));">
                        <span class="add-on" >грн</span>
                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="container">
        <section class="well">
            <a href="{% url export month year %}" class="btn btn-info">
                Экспорт в Excel
            </a>
        </section>

    </div>
    {% include 'paginator.html' %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Номер карты/канала</th>
            <th>Объект</th>
            <th>Местонахождение</th>
            <th>Номер концентратора</th>
            <th>Номер договора</th>
            <th>Дата заключения договора</th>
            <th>С кем заключён договор</th>
            <th>Начисленная абонплата </th>
            <th>Состояние</th>
        </tr>
        </thead>

        {% for card in cards %}
            <tbody>
            {% if card.cost or card|get_bill_by_month:date|first %}
            <tr>
                <td>
                    <a href="{{ card.get_absolute_url }}">
                        {{ card.number }}
                    </a>
                </td>
                <td>{{ card.object_set.all.0.name }}</td>
                <td>{{ card.object_set.all.0.address }} {% if card.object_set.all.0.branch.name   %}, {{ card.object_set.all.0.branch.name }}{% endif %}</td>
                <td>{{ card.object_set.all.0.hub.number }}</td>
                <td>{{ card.object_set.all.0.contract.number }}</td>
                <td>{{ card.object_set.all.0.contract.date }}</td>
                <td>{{ card.object_set.all.0.contract.contracted }}</td>
                <td>{% if card|get_bill_by_month:date %}{{ card|get_bill_by_month:date|first }} грн {% endif %}</td>
                <td>{{ card.get_state_display }}</td>
            </tr>
           {% endif %}
            </tbody>
        {% endfor %}
    </table>
    {% include 'paginator.html' %}
{% endblock %}

accounting/templates/paginator.html
{% if is_paginated %}
    <div class="pagination">
        <ul>
            {% if page_obj.has_previous %}
                <li>
                    <a href="/manager/cards_list/page{{ page_obj.previous_page_number }}/{{ month }}/{{ year }}/"> << </a>
                </li>
                {% ifnotequal page_obj.previous_page_number 1%}
                    <li>
                        <a href="/manager/cards_list/page1/{{ month }}/{{ year }}/">1</a>
                    </li>
                    <li class="disabled"><a href="#">...</a></li>
                {% endifnotequal %}
                <li>
                    <a href="/manager/cards_list/page{{ page_obj.previous_page_number }}/{{ month }}/{{ year }}/">{{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}
            <li class="active">
                <a>{{ page_obj.number }}</a>
            </li>
            {% if page_obj.has_next %}
                <li>
                    <a href="/manager/cards_list/page{{ page_obj.next_page_number }}/{{ month }}/{{ year }}/">{{ page_obj.next_page_number }}</a>
                </li>
                {% ifnotequal page_obj.next_page_number page_obj.paginator.num_pages %}
                    <li class="disabled"><a href="#">...</a></li>
                    <li>
                        <a href="/manager/cards_list/page{{ page_obj.paginator.num_pages  }}/{{ month }}/{{ year }}/">{{ page_obj.paginator.num_pages  }}</a>
                    </li>
                {% endifnotequal %}
                <li>
                    <a href="/manager/cards_list/page{{ page_obj.next_page_number }}/{{ month }}/{{ year }}/">>></a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

accounting/templates/upload_form.html
<form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
            <div class="row fileupload-buttonbar">
                <div class="span7">
                    <span class="btn btn-primary fileinput-button">
                        <i class="icon-plus icon-white"></i>
                        <span>Add files...</span>
                        <input type="file" name="file" multiple>
                    </span>
                    <button type="submit" class="btn btn-success start">
                        <i class="icon-upload icon-white"></i>
                        <span>Start upload</span>
                    </button>
                    <button type="reset" class="btn btn-warning cancel">
                        <i class="icon-ban-circle icon-white"></i>
                        <span>Cancel upload</span>
                    </button>
                    <button type="button" class="btn btn-danger delete">
                        <i class="icon-trash icon-white"></i>
                        <span>Delete files</span>
                    </button>
                    <input type="checkbox" class="toggle">
                </div>
                <div class="span5 fileupload-progress fade">
                    <div class="progress progress-success progres-striped active">
                        <div class="bar" style="width:0%"></div>
                    </div>
                    <div class="progress-extended">&nbsp;</div>
                </div>
            </div>
            <div class="fileupload-loading"></div>
            <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
        </form>

accounting/templates/uploadformbill.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-header" >
        <h1>Загрузка данных по счетам</h1>
    </div>
     {% include "upload_form.html" %}
     <div class="fileupload-content">
        <table class="files"></table>
        <div class="fileupload-progressbar"></div>
    </div>



{% endblock %}      

accounting/templates/uploadformpult.html
{% extends 'base.html' %}

{% block content %}


    <div class="page-header" >
        <h1>Загрузка  данных с пульта</h1>
    </div>
       {% include "upload_form.html" %}
        <div class="fileupload-content">
            <table class="files"></table>
            <div class="fileupload-progressbar"></div>
        </div>



{% endblock %}

accounting/templates/uploadincomeform.html
{% extends 'base.html' %}

{% block content %}


    <div class="page-header" >
        <h1>Загрузка  взятых объектов</h1>
    </div>
    {% include "upload_form.html" %}
    <div class="fileupload-content">
        <table class="files"></table>
        <div class="fileupload-progressbar"></div>
    </div>



{% endblock %}

accounting/templates/uploadoutcomeform.html
{% extends 'base.html' %}

{% block content %}


    <div class="page-header" >
        <h1>Загрузка ушедших объектов</h1>
    </div>
    {% include "upload_form.html" %}
    <div class="fileupload-content">
        <table class="files"></table>
        <div class="fileupload-progressbar"></div>
    </div>



{% endblock %}